### ISSUE TITLE
UDP support is missing

### ISSUE THREAD

**Issue by jprestwo** [Samsung/libtuv#24]
Libtuv currently does not have an implementation for UDP. Looking at the LibUV API's, all functions prefixed with uv_udp_\* have not been implemented. I saw that there is some code with commented out case statements containing UDP code paths so it would appear support may be in the works.

**Comment by seanshpark** [comment]
Hi, UDP is not on development currently and I don't have yet any plans to. It was just copied from with TCP and commented out cause maybe in the future it could be used. Do you have any needs to?

**Comment by yichoi** [comment]
#42 landed
