### ISSUE TITLE
Use of uv__udp_finish_close is Unix specific

### ISSUE THREAD

**Issue by nkolban** [Samsung/libtuv#47]
There is a reference to a function called uv__udp_finish_close() ... see:

https://github.com/Samsung/libtuv/blob/65b4efafc79fb79ab57554c5b729fa4fe695d6f7/source/uv_run.c#L68

That is defined only in the Unix specific implementation ...

https://github.com/Samsung/libtuv/blob/374e9978322d8173f385fd53297335b94e1787d1/source/unix/uv_unix_udp.c

I believe this needs to be abstracted.

**Comment by chokobole** [comment]
@nkolban I think the function signature itself is enough to be abstracted. (Because platform specific function signature we name this kind of function as `uv_unix_udp_finish_close`.) I believe the thing is needed is we implement more functions as we support more platforms.

**Comment by nkolban** [comment]
Howdy ... are you saying that the issue has been accepted as something that will be worked upon?  My goal is to port or get running libtuv on the new ESP32 platform and if changes are going to be made in this area, I'll hold off until done.

**Comment by chokobole** [comment]
Ah I assumed that you misunderstood my word `the thing is needed is we implement`. We don't plan to make a big work on this area. so If you want to extend our platform support, very welcome!

**Comment by nkolban** [comment]
I think we can track this as a duplicate of #49
