### ISSUE TITLE
Ever growing poll events table in nuttx.c

### ISSUE THREAD

**Issue by vprunet** [Samsung/libtuv#64]
Hi,

We have been unable to open/close more than 32 sockets (iot.js on STM32F4).

It seems to be related to the management of poll events in [libtuv/src/unix/nuttx.c](url).
Here is a summary of what we found:

- uv_add_pollfd should check that loop->npollfds is always less than the fixed size of the array (TUV_POLL_EVENTS_SIZE, which defaults to 32)

- uv__platform_invalidate_fd should restructure the array (like uv_rem_poll_fd) instead of just marking invalidated fd.

- uv_rem_pollfd, which would keep the pollfds table from growing,  is unfortunately never called (because of the invalidation of the fd done in uv__platform_invalidate_fd).

Hope this helps.

Cedric & Vincent

**Comment by glistening** [comment]
Thanks so much for informing us the bug and giving the guide. We will start to investigate this issue as soon as other ongoing tasks are resolved. Also, could you provide us the test code that caused this issue? It would help us much further to fix this issue.

**Comment by vprunet** [comment]
Here is a simple test code. For this, we use an STM32F4 board, with ethernet BB, connected to a server (10.0.1.2) running node.js.

Server code (node.js):
`
var net = require( 'net' );
var host = '10.0.1.2';
var port = 8889;
var timeout = 100;
var server = net.createServer( function( socket ) {
   console.log( 'New connection', socket.remoteAddress, socket.remotePort );
   setTimeout( function() {
      socket.destroy();
   }, timeout );
});

server.listen( port, host, function() {
   console.log( 'Server listening on', server.address() );
} );
`

Client code (iot.js on STM32F4):
`
var net = require( 'net' );
var host = '10.0.1.2';
var port = 8889;
var count = 0;

console.log( 'starting ...' );
function loop() {
   var client = new net.Socket();
   client.connect( port, host, function() {
      console.log( 'count', ++count );
   });
   client.on( 'end', function() {
      client.destroy();
      loop();
   });
   client.on( 'error', function( err ) {
      console.log( 'socket error' );
   });
}

loop();
`
The client opens a socket, the server then closes the socket. On the 'end' event, the client opens a new socket and so on.
The test crashes on iot.js while opening the 32nd socket.
When a patch is applied to uv__platform_invalidate (essentially copying the code from uv__rem_pollfd) the test sequence continues without error.

**Comment by glistening** [comment]
Thank you!
